name: 'it_helpdesk'
version: '1.0.0'
profile: 'it_helpdesk'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

models:
  it_helpdesk:
    staging:
      +database: DEV_STAGE
      +schema: IT_HELPDESK
      +materialized: view
    intermediate:
      +database: DEV_STAGE
      +schema: IT_HELPDESK
      +materialized: view
    dims:
      +database: DEV_MARTS
      +schema: IT_HELPDESK
      +materialized: table
      +persist_docs:
        relation: true
        columns: true
    marts:
      +database: DEV_MARTS
      +schema: IT_HELPDESK
      +materialized: table
      +persist_docs:
        relation: true
        columns: true
